### ISSUE TITLE
Not showing details under the mouse pointer - win 11

### ISSUE THREAD

**Issue by manojmanivannan** [chrisant996/elucidisk#1]
hi, First of all, i really like this tool. I installed on my windows 11 PC and immediately noticed that the mouse has to be a little offset, in order for the item to highlight and show the stats. See video below for the issue.

https://github.com/chrisant996/elucidisk/assets/23746043/5300e76c-a611-4f4b-856d-d86e6300b0c0

**Comment by chrisant996** [comment]
It's a DPI issue.  It looks like your monitor is 200% DPI, and apparently there's a bug in the DPI handling in the program.

**Comment by chrisant996** [comment]
Thanks for reporting the issue.  v0.21 has been published with proper DPI support.
