### ISSUE TITLE
App crashes when scanning for a folder

### ISSUE THREAD

**Issue by rigon** [chrisant996/elucidisk#2]
After opening the app, when we press the button to "Scan Folder", the app closes after selecting the folder.

**Comment by chrisant996** [comment]
Thanks for reporting this.  The regression was introduced in v1.0.

Commit 2487841a8a69347cd975e8f37c9132798f7f6ddd fixes it.

v1.1 has been published with the fix.

**Comment by rigon** [comment]
Tested, working now. Thanks!
