### ISSUE TITLE
Cross-platform port

### ISSUE THREAD

**Issue by rigon** [chrisant996/elucidisk#3]
Any plans to make it cross-platform? I see the app uses DirectX for rendering, which is Windows specific. I don't see any technical difficulty to implement it using OpenGL or Vulkan, however comes the hurdle of re-implementing many things.

I have to say, this is one of the best apps of this kind I've seen! It does its job really well. I have been using Scanner for a long time, but it has been an issue that doesn't work with folders >2TB. Your app is the perfect replacement. And I'm really pleased with the improvements you made over. It is also very nice to see your concern in making this app small (ridiculously small), something we don't see very often nowadays. There are other good similar apps that are good but many of them felt sluggish and bloated, but yours is completely in another level.

**Comment by chrisant996** [comment]
@rigon Thank you for the compliments.

I, too, have been using Scanner for a long time, and was very happy with it, apart from a few minor wishes.  It's no coincidence that Elucidisk looks and feels very similar to Scanner.  🙂

I don't use *nix or Mac, so a cross-platform port isn't something I'd invest in at this time.  If someone else wants to port it, I'm happy to discuss how to adjust the classes and abstraction/encapsulation boundaries to better facilitate cross-platform support.
